spring.application.name=event-tickets

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

api.security.token.secret=${API_SECURITY_TOKEN_SECRET:uma-chave-secreta-de-teste-para-desenvolvimento-local-123}

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true