spring.application.name=event-tickets

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/event_tickets}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:event_tickets}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:event_tickets}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

api.security.token.secret=${API_SECURITY_TOKEN_SECRET:uma-chave-secreta-de-teste-para-desenvolvimento-local-123}

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true